vars:
  BUNDLE_ID:
    default: com.tommylabs.portalzcu
  PACKAGE_NAME:
    default: com.tommylabs.portalzcu
  REQUIRED_VARIABLE:

platforms:
  ios:
    targets:
      App:
        bundleId: $BUNDLE_ID
        version: '3.0'
  #        buildNumber: 198
  #        productName: Awesome App
  #        displayName: My Awesome App
  #
  #        buildSettings:
  #        ENABLE_BITCODE: false
  #        STRIP_SWIFT_SYMBOLS: false

  #        plist:
  #          replace: false
  #          entries:
  #            - NSAppTransportSecurity: # povoli i HTTP requesty
  #                NSAllowsArbitraryLoads: true
  android:
    packageName: $PACKAGE_NAME
    versionName: '3.0'
    incrementVersionCode: false

    manifest:
      - file: AndroidManifest.xml
        target: manifest/application
#        attrs:
#          android:usesCleartextTraffic: true # povoli i HTTP requesty
